services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: location_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
