# Generated by Django 6.0.3 on 2026-03-25 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('type_bien', models.CharField(choices=[('Habitation', [('STUDIO', 'Studio'), ('T1', 'T1'), ('T2', 'T2'), ('T3+', 'T3+'), ('MAISON', 'Maison'), ('LOFT', 'Loft'), ('VILLA', 'Villa')]), ('Professionnel', [('BUREAU', 'Bureau'), ('COWORKING', 'Coworking'), ('COMMERCIAL', 'Local commercial'), ('ENTREPOT', 'Entrepôt')]), ('Spécifique', [('PARKING', 'Parking/Box'), ('TERRAIN', 'Terrain nu'), ('CAVE', 'Cave'), ('GARAGE', 'Garage')])], max_length=50)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUE', 'Loué'), ('VENDU', 'Vendu'), ('TRAVAUX', 'En travaux'), ('COMPROMIS', 'Sous compromis'), ('RESERVE', 'Réservé')], default='DISPONIBLE', max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('quartier', models.CharField(max_length=100)),
                ('ville', models.CharField(default='Lomé', max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('superficie', models.FloatField()),
                ('chambres', models.IntegerField(default=0)),
                ('salles_de_bain', models.IntegerField(default=0)),
                ('ascenseur', models.BooleanField(default=False)),
                ('climatisation', models.BooleanField(default=False)),
                ('cuisine_equipee', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='biens/')),
                ('is_main', models.BooleanField(default=False)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='biens.bien')),
            ],
        ),
    ]
