# Generated by Django 5.2.11 on 2026-03-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField(verbose_name="Date d'entrée")),
                ('date_sortie', models.DateField(verbose_name='Date de sortie prévue')),
                ('depot_garantie', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Dépôt de garantie (CFA)')),
                ('loyer_initial', models.DecimalField(decimal_places=2, help_text='Loyer au moment de la signature du bail', max_digits=12, verbose_name='Loyer initial (CFA)')),
                ('taux_revision_annuel', models.FloatField(default=0.0, help_text='Ex : 2.0 pour 2% par an', verbose_name='Taux de révision annuel (%)')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('EXPIRE', 'Expiré'), ('RESILE', 'Résilié'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Bail',
                'verbose_name_plural': 'Baux',
                'ordering': ['-date_entree'],
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(help_text='Rue, quartier, ville', max_length=255, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Description')),
                ('photos', models.JSONField(default=list, help_text='Liste de chemins ou URLs — max 20 photos', verbose_name='Photos')),
                ('equipements', models.JSONField(default=list, help_text="Ex : ['ascenseur', 'climatisation', 'parking']", verbose_name='Équipements')),
                ('loyer_hc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loyer hors charges (CFA)')),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Provisions charges (CFA)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude GPS')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude GPS')),
                ('statut', models.CharField(choices=[('LOUE', 'Loué'), ('VACANT', 'Vacant'), ('VENDRE', 'À vendre'), ('EN_TRAVAUX', 'En travaux')], default='VACANT', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Biens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé (CFA)')),
                ('reference', models.CharField(help_text='Ex : numéro de reçu T-Money / Flooz', max_length=100, unique=True, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('PAYE', 'Payé'), ('EN_ATTENTE', 'En attente'), ('EN_RETARD', 'En retard'), ('FIN_BAIL_PROCHE', 'Fin de bail proche'), ('VALIDE', 'Validé'), ('IMPAYE', 'Impayé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total (CFA)')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='quittances/pdfs/', verbose_name='Fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Quittance',
                'verbose_name_plural': 'Quittances',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='TypeAppartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': "Type d'appartement",
                'verbose_name_plural': "Types d'appartement",
                'ordering': ['libelle'],
            },
        ),
    ]
