# Generated by Django 5.2.11 on 2026-03-16 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baux', to='utilisateur.locataire', verbose_name='Locataire'),
        ),
        migrations.AddField(
            model_name='bien',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='utilisateur.proprietaire', verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='bail',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baux', to='biens.bien', verbose_name='Bien'),
        ),
        migrations.AddField(
            model_name='bien',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biens', to='biens.categorie', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='bail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='biens.bail', verbose_name='Bail'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='utilisateur.locataire', verbose_name='Locataire'),
        ),
        migrations.AddField(
            model_name='quittance',
            name='paiement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quittance', to='biens.paiement', verbose_name='Paiement associé'),
        ),
        migrations.AddField(
            model_name='bien',
            name='type_appartement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='biens.typeappartement', verbose_name="Type d'appartement"),
        ),
    ]
