# Generated by Django 5.2.1 on 2026-03-19 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='photos',
        ),
        migrations.CreateModel(
            name='PhotoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Formats acceptés : JPG, PNG, WEBP — Max 5 Mo', upload_to='biens/photos/%Y/%m/', verbose_name='Fichier image')),
                ('image_base64', models.TextField(blank=True, help_text="Rempli automatiquement à la sauvegarde via l'API", verbose_name='Image encodée (Base64)')),
                ('legende', models.CharField(blank=True, help_text='Ex : Chambre principale, Cuisine, Vue de la terrasse', max_length=200, verbose_name='Légende')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='0 = photo principale', verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_bien', to='biens.bien', verbose_name='Bien')),
            ],
            options={
                'verbose_name': 'Photo du bien',
                'verbose_name_plural': 'Photos du bien',
                'ordering': ['bien', 'ordre'],
            },
        ),
    ]
