# Generated by Django 5.2.11 on 2026-03-20 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0003_remove_bien_photos_photobien'),
        ('utilisateur', '0002_alter_admin_managers_alter_locataire_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bail',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bails', to='biens.bien', verbose_name='Bien'),
        ),
        migrations.AlterField(
            model_name='bail',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bails', to='utilisateur.locataire', verbose_name='Locataire'),
        ),
    ]
