# Generated by Django 5.2.11 on 2026-03-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0004_alter_bail_bien_alter_bail_locataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Formats acceptés : MP4, AVI, MOV, WEBM — Max 50 Mo', upload_to='biens/videos/%Y/%m/', verbose_name='Fichier vidéo')),
                ('thumbnail', models.ImageField(blank=True, help_text='Image de prévisualisation de la vidéo', null=True, upload_to='biens/videos/thumbnails/%Y/%m/', verbose_name='Miniature')),
                ('titre', models.CharField(blank=True, help_text='Ex : Visite virtuelle, Tour de la propriété', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duree', models.IntegerField(blank=True, help_text='Durée de la vidéo en secondes', null=True, verbose_name='Durée (secondes)')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_bien', to='biens.bien', verbose_name='Bien')),
            ],
            options={
                'verbose_name': 'Vidéo du bien',
                'verbose_name_plural': 'Vidéos du bien',
                'ordering': ['bien', 'ordre'],
            },
        ),
    ]
