# Generated by Django 6.0.3 on 2026-04-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0005_videobien'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='commission_admin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='10% du montant du paiement', max_digits=12, verbose_name='Commission administrateur (CFA)'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_proprietaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='90% du montant du paiement', max_digits=12, verbose_name='Montant net propriétaire (CFA)'),
        ),
    ]
