# Generated by Django 6.0.3 on 2026-04-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0006_paiement_commission_admin_and_more'),
        ('utilisateur', '0003_twofactorauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENT', 'Urgent')], default='MOYENNE', max_length=20, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('cout_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Coût estimé (CFA)')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='biens.bien', verbose_name='Bien')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances_signalees', to='utilisateur.locataire', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
