# Generated by Django 6.0.3 on 2026-04-03 13:37

from django.db import migrations

def seed_data(apps, schema_editor):
    Categorie = apps.get_model('biens', 'Categorie')
    TypeAppartement = apps.get_model('biens', 'TypeAppartement')

    # Catégories par défaut
    categories = [
        {'libelle': 'Appartement', 'description': 'Logement dans un immeuble collectif'},
        {'libelle': 'Maison', 'description': 'Habitation individuelle'},
        {'libelle': 'Villa', 'description': 'Maison de standing avec jardin'},
        {'libelle': 'Bureau', 'description': 'Espace de travail professionnel'},
        {'libelle': 'Boutique', 'description': 'Local commercial'},
        {'libelle': 'Chambre', 'description': 'Chambre individuelle (ex: entrée-coucher)'},
    ]

    for cat in categories:
        Categorie.objects.get_or_create(libelle=cat['libelle'], defaults={'description': cat['description']})

    # Types d'appartement par défaut
    types = [
        {'libelle': 'Studio', 'description': 'Une pièce principale avec coin cuisine'},
        {'libelle': 'F1', 'description': 'Une pièce + cuisine séparée'},
        {'libelle': 'F2', 'description': 'Salon + 1 chambre'},
        {'libelle': 'F3', 'description': 'Salon + 2 chambres'},
        {'libelle': 'F4', 'description': 'Salon + 3 chambres'},
        {'libelle': 'F5', 'description': 'Salon + 4 chambres'},
        {'libelle': 'Chambre salon', 'description': 'Une chambre et un salon (classique au Togo)'},
    ]

    for t in types:
        TypeAppartement.objects.get_or_create(libelle=t['libelle'], defaults={'description': t['description']})

def remove_seed_data(apps, schema_editor):
    Categorie = apps.get_model('biens', 'Categorie')
    TypeAppartement = apps.get_model('biens', 'TypeAppartement')
    
    Categorie.objects.all().delete()
    TypeAppartement.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0007_maintenance'), # Dépend de la migration précédente réelle
    ]

    operations = [
        migrations.RunPython(seed_data, remove_seed_data),
    ]
