# Generated by Django 6.0.3 on 2026-04-03 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0009_seed_categories_types'),
        ('utilisateur', '0005_remove_utilisateur_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Acceptée'), ('REFUSE', 'Refusée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='biens.bien', verbose_name='Bien')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='utilisateur.locataire', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
