# Generated by Django 6.0.3 on 2026-04-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0010_candidature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='equipements',
            field=models.JSONField(blank=True, default=list, help_text="Ex : ['ascenseur', 'climatisation', 'parking']", verbose_name='Équipements'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='statut',
            field=models.CharField(choices=[('LOUE', 'Loué'), ('VACANT', 'Vacant'), ('VENDRE', 'À vendre'), ('SOUS_COMPROMIS', 'Sous compromis'), ('VENDU', 'Vendu'), ('EN_TRAVAUX', 'En travaux')], default='VACANT', max_length=20, verbose_name='Statut'),
        ),
    ]
