# Generated by Django 6.0.3 on 2026-04-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0011_alter_bien_equipements_alter_bien_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='date_envoi_justificatif',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi du justificatif"),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='justificatif',
            field=models.ImageField(blank=True, null=True, upload_to='maintenances/justificatifs/%Y/%m/', verbose_name='Justificatif (photo/reçu)'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='justificatif_commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire justificatif'),
        ),
    ]
