# Generated by Django 6.0.3 on 2026-03-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='cni',
            field=models.FileField(blank=True, null=True, upload_to='dossiers/cni/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='fiche_paie',
            field=models.FileField(blank=True, null=True, upload_to='dossiers/paie/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nationalite',
            field=models.CharField(default='Togolaise', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='revenus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
    ]
