# Generated by Django 5.2.11 on 2026-03-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemeComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField(help_text='Date de début de la période comptable', verbose_name='Début de période')),
                ('periode_fin', models.DateField(blank=True, help_text='Date de fin de la période comptable (optionnel)', null=True, verbose_name='Fin de période')),
                ('total_revenus', models.DecimalField(decimal_places=2, default=0, help_text='Somme des loyers perçus sur la période', max_digits=15, verbose_name='Total revenus (CFA)')),
                ('total_depense', models.DecimalField(decimal_places=2, default=0, help_text='Somme des dépenses : travaux, taxes, frais divers', max_digits=15, verbose_name='Total dépenses (CFA)')),
                ('benefice_net', models.DecimalField(decimal_places=2, default=0, help_text='Calculé : total_revenus - total_depense', max_digits=15, verbose_name='Bénéfice net (CFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Système comptable',
                'verbose_name_plural': 'Systèmes comptables',
                'ordering': ['-periode_debut'],
            },
        ),
    ]
