# Generated by Django 5.2.11 on 2026-03-16 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemecomptable',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systemes_comptables', to='utilisateur.proprietaire', verbose_name='Propriétaire'),
        ),
    ]
