# Generated by Django 6.0.3 on 2026-04-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemecomptable',
            name='total_commission_admin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Somme des 10% prélevés sur les loyers validés', max_digits=15, verbose_name='Total commission administrateur (CFA)'),
        ),
        migrations.AlterField(
            model_name='systemecomptable',
            name='total_revenus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Somme nette propriétaire (90% des loyers validés)', max_digits=15, verbose_name='Total revenus (CFA)'),
        ),
    ]
