# Generated by Django 5.2.11 on 2026-03-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Contenu de la notification', verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('type', models.CharField(choices=[('LOYER_IMPAYE', 'Loyer impayé'), ('FIN_BAIL_PROCHE', 'Fin de bail proche (3 mois)'), ('REVISION_LOYER', 'Révision annuelle du loyer'), ('QUITTANCE', 'Quittance disponible'), ('DOCUMENT', 'Document généré (bail, état des lieux…)')], max_length=30, verbose_name='Type de notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
