# Generated by Django 5.2.11 on 2026-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='lue',
        ),
        migrations.AddField(
            model_name='notification',
            name='lu',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(default='Notification', help_text='Titre de la notification', max_length=200, verbose_name='Titre'),
        ),
    ]
