# Generated by Django 6.0.3 on 2026-03-26 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0002_candidature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode', models.CharField(choices=[('TMONEY', 'T-Money'), ('FLOOZ', 'Flooz'), ('VIREMENT', 'Virement Bancaire')], max_length=20)),
                ('preuve', models.ImageField(upload_to='paiements/preuves/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='biens.bien')),
                ('candidature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='biens.candidature')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
