# Generated by Django 5.2.11 on 2026-03-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admin',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='locataire',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='proprietaire',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
