# Generated by Django 5.2.11 on 2026-03-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_alter_admin_managers_alter_locataire_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_secret', models.CharField(blank=True, help_text='Secret pour Google Authenticator', max_length=32, verbose_name='Secret TOTP')),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='Liste de codes de secours à usage unique', verbose_name='Codes de secours')),
                ('email_code', models.CharField(blank=True, help_text='Code de vérification envoyé par email', max_length=6, verbose_name='Code email')),
                ('email_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création du code email')),
                ('methode', models.CharField(choices=[('TOTP', 'Google Authenticator (TOTP)'), ('EMAIL', 'Code par email')], default='TOTP', max_length=10, verbose_name='Méthode 2FA')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='2FA activé')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Authentification à deux facteurs',
                'verbose_name_plural': 'Authentifications à deux facteurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
