# Generated by Django 6.0.3 on 2026-04-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_create_default_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='first_name',
        ),
    ]
