# Generated by Django 6.0.3 on 2026-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_remove_utilisateur_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='cni',
            field=models.ImageField(blank=True, null=True, upload_to='locataires/cni/', verbose_name="Pièce d'identité"),
        ),
        migrations.AddField(
            model_name='locataire',
            name='fiche_paie',
            field=models.FileField(blank=True, null=True, upload_to='locataires/fiches_paie/', verbose_name='Fiches de paie'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='garant_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du garant'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='garant_lien',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lien avec le garant'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='garant_nom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du garant'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='garant_profession',
            field=models.CharField(blank=True, max_length=150, verbose_name='Profession du garant'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='garant_revenus',
            field=models.PositiveIntegerField(default=0, verbose_name='Revenus du garant'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='garant_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du garant'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='nationalite',
            field=models.CharField(default='Togolaise', max_length=100, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='revenus',
            field=models.PositiveIntegerField(default=0, verbose_name='Revenus mensuels'),
        ),
    ]
