# Generated by Django 6.0.3 on 2026-04-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_locataire_cni_locataire_fiche_paie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Indique si les documents ont été validés par l'administration", verbose_name='Profil vérifié'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='trust_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Score de confiance'),
        ),
    ]
